export const ASTRYX_TABLE_COMMIT_PROBE_DIAGNOSTIC_SENTINEL =
  "ASTRYX_TABLE_COMMIT_PROBE_DIAGNOSTIC_V1";

export const ASTRYX_TABLE_GESTURE_TIMING_DIAGNOSTIC_SENTINEL =
  "ASTRYX_TABLE_GESTURE_TIMING_DIAGNOSTIC_V1";

export const ASTRYX_TABLE_CELL_RANGE_FRAME_TIMING_DIAGNOSTIC_SENTINEL =
  "ASTRYX_TABLE_CELL_RANGE_FRAME_TIMING_DIAGNOSTIC_V1";

export const ASTRYX_TABLE_TEST_LISTENER_DIAGNOSTIC_SENTINEL =
  "ASTRYX_TABLE_TEST_LISTENER_DIAGNOSTIC_V1";
